/**
 * GENERATED by `pnpm brand:mobile` — do not edit by hand.
 *
 * Venue: Rangla Punjab Restaurant · Konstanz (rangla-punjab) · menu theme: rangla-royal
 * Every pairing the screens rely on (ink on cream, gold on red, ink on the
 * gold CTA fill …) clears WCAG AA by construction — see
 * src/lib/mobile-brand.ts in the web app.
 */

export const brand = {
  name: "Rangla Punjab Restaurant · Konstanz",
  slug: "rangla-punjab",
  themeId: "rangla-royal",
  /** The venue advertises a halal kitchen (`branding.halalFilter === "on"`).
   *  Gates the calligraphic حلال mark on the welcome screen. */
  halal: true,
} as const;

export const colors = {
  red: "#8f1a1a",
  redDark: "#701414",
  cream: "#fdf4e0",
  creamCard: "#fef9ee",
  gold: "#8b6914",
  goldSoft: "#e8c15c",
  ink: "#360a0a",
  inkSoft: "#7a5d5d",
  line: "#e1d3c2",
  onRed: "#fdf3dd",
  positive: "#397e4c",
  danger: "#a4231b",
} as const;

/** Wash between the hero artwork and the text over it — see deriveScrim. */
export const scrim = "rgba(112, 20, 20, 0.78)";

/** The venue logo, rasterised next to the app icons by the same script. */
export const logo = require("../assets/generated/logo.png");

/** Hero artwork: the venue's banner, its menu backdrop, or a palette gradient. */
export const hero = require("../assets/generated/hero.jpg");
